### ISSUE TITLE
RCLONE

### ISSUE THREAD

**Issue by javsubs91** [developeranaz/heroku-jupyter-BETA#2]
how to mount rclone into this notebook?

**Comment by developeranaz** [comment]
I couldn't do that mount in this heroku server
and maybe some required pakages added before the deployment in heroku could works the mount, but why mounting your cloud in heroku. 

In my opinion use rclone copy command

**Comment by javsubs91** [comment]
can you write an example command?

**Comment by developeranaz** [comment]
why mounting, 
i tried to mount but i couldn't. Its showing libfuse error.

**Comment by javsubs91** [comment]
I want to transfer the files that I have downloaded to my gdrive

**Comment by javsubs91** [comment]
thank you very much for your response. I have found the way

**Comment by javsubs91** [comment]
your repo is awesome
