### ISSUE TITLE
Sudo / Su access?

### ISSUE THREAD

**Issue by treastershawn** [developeranaz/heroku-jupyter-BETA#3]
Hey there , is it possible to gain root privileges on the server terminal ?

**Comment by developeranaz** [comment]
you can't use root privileges after  the app is deployed, heroku limit that feature.
but during deployment time you can have some root permissions like installing apps etc..

**Comment by treastershawn** [comment]
> you can't use root privileges after the app is deployed, heroku limit that feature. but during deployment time you can have some root permissions like installing apps etc..

Thanks for explaining and help 👍
